#!/usr/bin/env python3
"""
Embed the Stardew theme stylesheet as a self-contained JS module.

Reads src/styles/stardew.css and rewrites every local `url('./*.png|gif')`
reference into a base64 data URI, emitting src/client/theme-css.ts so the
bundled client plugin can inject the full theme (images included) at runtime
without serving separate asset files.

Usage:
    python3 scripts/embed-css.py
"""
import base64
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
STYLES = os.path.join(ROOT, 'src', 'styles')
OUT = os.path.join(ROOT, 'src', 'client', 'theme-css.ts')

MIME = {
    '.png': 'image/png',
    '.gif': 'image/gif',
    '.svg': 'image/svg+xml',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
}


def inline(match: re.Match) -> str:
    file = match.group(1)
    path = os.path.join(STYLES, file)
    if not os.path.exists(path):
        print(f'  ! unresolved: {file}')
        return match.group(0)
    ext = os.path.splitext(file)[1].lower()
    mime = MIME.get(ext, 'application/octet-stream')
    b64 = base64.b64encode(open(path, 'rb').read()).decode('ascii')
    return f'url("data:{mime};base64,{b64}")'


def main() -> None:
    css = open(os.path.join(STYLES, 'stardew.css'), encoding='utf-8').read()
    inline_css = re.sub(r"url\(['\"]?\.\/([^'\")\s]+)['\"]?\)", inline, css)
    remaining = set(re.findall(r"url\(['\"]?(\.[^'\")\s]+)['\"]?\)", inline_css))
    if remaining:
        print('WARN unresolved url() refs:', sorted(remaining))
    header = (
        '/* AUTO-GENERATED by scripts/embed-css.py — do not edit. */\n'
        '/* Self-contained Stardew theme stylesheet; every image inlined. */\n'
        'export const STARDEW_CSS = '
    )
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(header + json.dumps(inline_css) + '\n')
    print(f'✓ wrote {os.path.relpath(OUT, ROOT)} ({len(inline_css)} bytes)')


if __name__ == '__main__':
    main()
